GET http://localhost:3001/test 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhc3UiLCJpZCI6MjEsImlhdCI6MTYyMzk0MzgzMiwiZXhwIjoxNjIzOTQzODQ3fQ.cKWC4JL--xRxNRVE4acBa6SxSTkgxurHTXdLGU6k-jI